VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Sheet1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Sub Homework2():

'Set Dimensions
Dim total As Double
Dim i As Long
Dim change As Single
Dim j As Integer
Dim start As Long
Dim rowCount As Long
Dim percentChange As Single
Dim ws As Worksheet

For Each ws In Worksheets

MsgBox ws.Name

    'Set values for each worksheet
    j = 0
    total = 0
    change = 0
    start = 2


'Set title row
ws.Range("I1").Value = "Ticker"
ws.Range("J1").Value = "Yearly Change"
ws.Range("K1").Value = "Percent Change"well
ws.Range("L1").Value = "Total Stock Volume"

'Set inital values
j = 0
total = 0
change = 0
start = 2

'Get the row number of the last row with data
'rowCount = Cells(Rows.Count, ws.Name).End(xlUp).Row
rowCount = Cells(ws.Rows.Count, ws.Name).End(xlUp).Row
rowCount = Worksheets(ws.Name).UsedRange.Rows.Count




MsgBox rowCount

For i = 2 To rowCount

    'If ticker changes then print results
    If ws.Cells(i + 1, 1).Value <> ws.Cells(i, 1).Value Then
      
       'Stores results in variables
        total = total + ws.Cells(i, 7).Value

       'Handle zero total volume
       If total = 0 Then
           'Print the results
           ws.Range("I" & 2 + j).Value = Cells(i, 1).Value
           ws.Range("J" & 2 + j).Value = 0
           ws.Range("K" & 2 + j).Value = "%" & 0
           ws.Range("L" & 2 + j).Value = 0
           Else

         'Find first non-zero starting value
         If Cells(start, 3) = 0 Then
                 For find_value = start To i
           If Cells(find_value, 3).Value <> 0 Then
               start = find_value
               Exit For
            End If
          Next find_value
            End If
        
        'Calculate change
        change = (Cells(i, 6) - Cells(start, 3))
        If (Cells(start, 3) = 0) Then
            MsgBox Cells(start, 3)
            Cells(start, 3) = 1
        
        End If
        percentChange = Round((change / Cells(start, 3) * 100), 2)

        'Start of the next stock ticker
        start = i + 1

        'Print the results
        ws.Range("I" & 2 + j).Value = ws.Cells(i, 1).Value
        ws.Range("J" & 2 + j).Value = Round(change, 2)
        ws.Range("K" & 2 + j).Value = "%" & percentChange
        ws.Range("L" & 2 + j).Value = total

        'Colors positive green and negatives red
        Select Case change
           Case Is > 0
             ws.Range("J" & 2 + j).Interior.ColorIndex = 4
           Case Is < 0
             ws.Range("J" & 2 + j).Interior.ColorIndex = 3
           Case Else
             ws.Range("J" & 2 + j).Interior.ColorIndex = 0
        End Select
          End If

          'Reset variables for new stock ticker
          total = 0
              change = 0
          j = j + 1

    'If ticker is still the same add result
    Else
       total = total + ws.Cells(i, 7).Value
    End If

   Next i
   
Next ws
        
End Sub
